- name: Install MongoDB Component
  hosts: mongodb
  become: yes
  tasks: 
  - name: Copying mongo repo
    ansible.builtin.copy: 
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing MongoDB
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  
  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb-org
      state: started
      enable: yes
      
