- name: web component
  hosts: web
  become: yes
  tasks: 
  - name: Installing nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: Start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Remove files
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: downloading web files
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      path: /tmp
